In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


### Introduction to tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Converting tensor(the scalar object declared above) back to python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([2, 2])
vector

tensor([2, 2])

In [ ]:
vector.ndim

1

In [ ]:
# converting a vector to an array
array = vector.numpy()
array

array([2, 2])

In [ ]:
MATRIX = torch.tensor([[3, 8],
                      [47, 53]])
MATRIX

tensor([[ 3,  8],
        [47, 53]])

In [ ]:
MATRIX.ndim

2

In [ ]:
# converting a matrix into a flattened array
flat_array = MATRIX.numpy()
flat_array

array([[ 3,  8],
       [47, 53]])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1, 2, 4], [4, 7, 2], [34, 6, 9]]])
TENSOR

tensor([[[ 1,  2,  4],
         [ 4,  7,  2],
         [34,  6,  9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### random tensors

Why random tensors?

Most of the Neural Networks learn by starting with tensors of random numbers and then adjust
those random numbers to better represent the data

In [ ]:
# Creating random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5954, 0.0549, 0.2546, 0.9232],
        [0.2548, 0.8890, 0.2728, 0.9329],
        [0.2990, 0.6819, 0.9824, 0.7235]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor.ndim

2

In [ ]:
# creating random tensor of similar shape of image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 244)) # color-channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 244]), 3)

#### Tensor of zeros and ones

In [ ]:
# Tensor with all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Default torch datatype
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
torch.range(0, 10)

<ipython-input-26-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
help(torch.arange)

Help on built-in function arange in module torch:

arange(...)
    arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
    with values from the interval ``[start, end)`` taken with common difference
    :attr:`step` beginning from `start`.
    
    Note that non-integer :attr:`step` is subject to floating point rounding errors when
    comparing against :attr:`end`; to avoid inconsistency, we advise subtracting a small epsilon from :attr:`end`
    in such cases.
    
    .. math::
        \text{out}_{{i+1}} = \text{out}_{i} + \text{step}
    
    Args:
        start (Number): the starting value for the set of points. Default: ``0``.
        end (Number): the ending value for the set of points
        step (Number): the gap between each pair of adjacent points. Default: ``1``.
    
    Keyword args:
     

In [ ]:
range = torch.arange(start=0, end=1000, step=65)
range

tensor([  0,  65, 130, 195, 260, 325, 390, 455, 520, 585, 650, 715, 780, 845,
        910, 975])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note**

Three common errors seen in pytorch and deep learning:
1. Tensors are not right datatype.
2. Tensors are not right shape.
3. Tensors are not on the right device.

In [ ]:
# Importent parameters can be used while creating a tensor
float_tensor = torch.tensor([3.0, 6.0, 8.0],
                            dtype=torch.float16,
                            device = None,        # "cpu"(by default), "cuda"(for gpu multithreading)
                            requires_grad=False)  # Wheather or not to track gradients with this tensor operations
float_tensor, float_tensor.dtype

(tensor([3., 6., 8.], dtype=torch.float16), torch.float16)

In [ ]:
# converting the float16 type tensor to float32
float_32_tensor = float_tensor.type(torch.float32)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 8.]), torch.float32)

### Tensor Multiplication

In [ ]:
output = float_tensor * float_32_tensor
output, output.dtype

(tensor([ 9., 36., 64.]), torch.float32)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
output = int_32_tensor * float_32_tensor
output, output.dtype

(tensor([ 9., 36., 72.]), torch.float32)

### Getting information from TENSORS (Tensor Attributes)
1. Tensors are not right datatype       : To get datatype of tensor, can use tensor.dtype
2. Tensors are not right shape.         : To get shape of tensor, can use tensor.shape   
3. Tensors are not on the right device. : To get device of tensor, can use tensor.device

In [ ]:
test_tensor = torch.rand(3, 4)
test_tensor

tensor([[0.5947, 0.0900, 0.2005, 0.5998],
        [0.5288, 0.3884, 0.3936, 0.5253],
        [0.8917, 0.6033, 0.8784, 0.0909]])

In [ ]:
print(f"Datatype: {test_tensor.dtype}")
print(f"Shape: {test_tensor.shape}")
print(f"Device: {test_tensor.device}")

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Additoin
* Subtraction
* Multiplication (Element wise)
* Division
* Matrix Multiplication

In [ ]:
# Addition:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 20

tensor([20, 40, 60])

In [ ]:
# PyTorch in-built functions
torch.mul(tensor, 100)

tensor([100, 200, 300])

In [ ]:
### Matrix Multiplication

In [ ]:
# Dot product matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.13 ms, sys: 869 µs, total: 2 ms
Wall time: 5.01 ms


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 150 µs, sys: 0 ns, total: 150 µs
Wall time: 155 µs


tensor(14)

In [ ]:
T1 = torch.rand(size=(244, 244, 2))
T2 = torch.rand(size=(2,2))
torch.matmul(T1, T2)

tensor([[[0.2976, 0.3965],
         [0.2427, 0.4588],
         [0.5278, 0.7439],
         ...,
         [0.5368, 0.7419],
         [0.6615, 0.9399],
         [0.4039, 0.6975]],

        [[0.6174, 0.7899],
         [0.5504, 0.7423],
         [0.5913, 0.6628],
         ...,
         [0.1496, 0.2907],
         [0.1662, 0.3086],
         [0.7107, 1.0826]],

        [[0.1984, 0.3295],
         [0.3396, 0.5994],
         [0.6257, 0.8997],
         ...,
         [0.5857, 0.6994],
         [0.4231, 0.6647],
         [0.5603, 0.7266]],

        ...,

        [[0.3580, 0.6753],
         [0.3522, 0.5943],
         [0.1390, 0.1936],
         ...,
         [0.1460, 0.3913],
         [0.2795, 0.5987],
         [0.6536, 0.7976]],

        [[0.5226, 0.8410],
         [0.4355, 0.6645],
         [0.1907, 0.4073],
         ...,
         [0.5397, 0.6142],
         [0.3558, 0.5647],
         [0.1917, 0.4546]],

        [[0.7153, 0.9289],
         [0.3558, 0.6986],
         [0.4186, 0.4792],
         ...,
 

### To fix tensor shape issues, we can use matrix transpose
A Transpose switches the axis or the dimentions of a given tensor

In [ ]:
T1 = torch.rand(2, 3)
T1.shape

torch.Size([2, 3])

In [ ]:
transpose_T1 = T1.T
transpose_T1.shape

torch.Size([3, 2])

In [ ]:
T1, transpose_T1

(tensor([[0.5161, 0.5971, 0.1032],
         [0.9808, 0.6300, 0.9974]]),
 tensor([[0.5161, 0.9808],
         [0.5971, 0.6300],
         [0.1032, 0.9974]]))

In [ ]:
torch.matmul(T1, transpose_T1)

tensor([[0.6335, 0.9853],
        [0.9853, 2.3538]])

### Finding the min, max, mean, sum, etc (tensor aggrigation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.max()

(tensor(0), tensor(90))

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
 torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

### Tensor Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1,19)
x, x.dtype, x.ndim

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
 torch.int64,
 1)

In [ ]:
x = x.type(torch.float32)
x.dtype

torch.float32

In [ ]:
x_reshape = x.reshape(1, 7)
x_reshape, x_reshape.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 18

In [ ]:
# Add an extra dimention
x_re = x.reshape(1, 18)
x_re, x_re.shape, x_re.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18.]]),
 torch.Size([1, 18]),
 2)

In [ ]:
x_re = x.reshape(18, 1)
x_re, x_re.shape, x_re.ndim

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.],
         [15.],
         [16.],
         [17.],
         [18.]]),
 torch.Size([18, 1]),
 2)

In [ ]:
# 2 dimentional reshape
x_2d_re = x_re.reshape(9, 2)
x_2d_re, x_2d_re.shape, x_2d_re.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [13., 14.],
         [15., 16.],
         [17., 18.]]),
 torch.Size([9, 2]),
 2)

In [ ]:
# Change the view
# similar to reshape (but reshape does not create a new copy of tensor it uses the memory of the input tensor itself)
# this is kind of a call by reference in c
T = torch.range(1, 9)
T.shape, T

<ipython-input-79-4b799132efb3>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  T = torch.range(1, 9)


(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
z = T.view(9, 1)
z.shape, z

(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
T.shape, T

(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked_hstack = torch.stack([T,T,T,T], dim=0)
x_stacked_vstack = torch.stack([T,T,T,T], dim=1)
x_stacked_hstack, x_stacked_vstack, x_stacked_vstack.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
# torch.squeeze() - removes all single dimention from a target tensor
x_st_v_re = x_stacked_vstack.reshape(1, 9, 4)
x_st_v_re, x_st_v_re.ndim

(tensor([[[1., 1., 1., 1.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.],
          [4., 4., 4., 4.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.],
          [7., 7., 7., 7.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 3)

In [ ]:
x_sqz = x_st_v_re.squeeze()
x_sqz, x_sqz.ndim

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 2)

In [ ]:
# torch.unsqueeze() - adds a single dimention to a target tensor at a specific dimension.
x_unsqz = x_sqz.unsqueeze(dim=0)
x_unsqz, x_unsqz.shape, x_unsqz.ndim

(tensor([[[1., 1., 1., 1.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.],
          [4., 4., 4., 4.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.],
          [7., 7., 7., 7.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 torch.Size([1, 9, 4]),
 3)

In [ ]:
x_unsqz = x_sqz.unsqueeze(dim=1)
x_unsqz, x_unsqz.shape, x_unsqz.ndim

(tensor([[[1., 1., 1., 1.]],
 
         [[2., 2., 2., 2.]],
 
         [[3., 3., 3., 3.]],
 
         [[4., 4., 4., 4.]],
 
         [[5., 5., 5., 5.]],
 
         [[6., 6., 6., 6.]],
 
         [[7., 7., 7., 7.]],
 
         [[8., 8., 8., 8.]],
 
         [[9., 9., 9., 9.]]]),
 torch.Size([9, 1, 4]),
 3)

In [ ]:
x_unsqz = x_sqz.unsqueeze(dim=2)
x_unsqz, x_unsqz.shape, x_unsqz.ndim

(tensor([[[1.],
          [1.],
          [1.],
          [1.]],
 
         [[2.],
          [2.],
          [2.],
          [2.]],
 
         [[3.],
          [3.],
          [3.],
          [3.]],
 
         [[4.],
          [4.],
          [4.],
          [4.]],
 
         [[5.],
          [5.],
          [5.],
          [5.]],
 
         [[6.],
          [6.],
          [6.],
          [6.]],
 
         [[7.],
          [7.],
          [7.],
          [7.]],
 
         [[8.],
          [8.],
          [8.],
          [8.]],
 
         [[9.],
          [9.],
          [9.],
          [9.]]]),
 torch.Size([9, 4, 1]),
 3)

In [ ]:
# torch.permute = rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(255, 224, 3)

x_permuted = x_original.permute(2, 0, 1)

x_original.shape, x_permuted.shape

(torch.Size([255, 224, 3]), torch.Size([3, 255, 224]))

In [ ]:
x_original

tensor([[[0.8758, 0.8617, 0.3533],
         [0.6513, 0.7785, 0.1573],
         [0.8718, 0.9740, 0.5367],
         ...,
         [0.5216, 0.5043, 0.6005],
         [0.5900, 0.8297, 0.4711],
         [0.6719, 0.2106, 0.3447]],

        [[0.5385, 0.0739, 0.1721],
         [0.7184, 0.6594, 0.6479],
         [0.6324, 0.3695, 0.1323],
         ...,
         [0.9176, 0.1167, 0.5191],
         [0.4619, 0.8271, 0.9200],
         [0.4695, 0.2062, 0.7225]],

        [[0.6162, 0.9073, 0.7120],
         [0.2231, 0.9649, 0.1368],
         [0.4984, 0.5037, 0.2871],
         ...,
         [0.9687, 0.9057, 0.1842],
         [0.0543, 0.6691, 0.4571],
         [0.6771, 0.5773, 0.6711]],

        ...,

        [[0.9810, 0.8122, 0.8538],
         [0.6358, 0.7406, 0.5409],
         [0.2094, 0.1205, 0.0052],
         ...,
         [0.1101, 0.0920, 0.3256],
         [0.5611, 0.9817, 0.7855],
         [0.7013, 0.1033, 0.0844]],

        [[0.9632, 0.9988, 0.2247],
         [0.8677, 0.0014, 0.5855],
         [0.

In [ ]:
x_original[0, 0, 0]

tensor(0.8758)

In [ ]:
x_original[0, 0, 0] = 0
x_original

tensor([[[0.0000, 0.8617, 0.3533],
         [0.6513, 0.7785, 0.1573],
         [0.8718, 0.9740, 0.5367],
         ...,
         [0.5216, 0.5043, 0.6005],
         [0.5900, 0.8297, 0.4711],
         [0.6719, 0.2106, 0.3447]],

        [[0.5385, 0.0739, 0.1721],
         [0.7184, 0.6594, 0.6479],
         [0.6324, 0.3695, 0.1323],
         ...,
         [0.9176, 0.1167, 0.5191],
         [0.4619, 0.8271, 0.9200],
         [0.4695, 0.2062, 0.7225]],

        [[0.6162, 0.9073, 0.7120],
         [0.2231, 0.9649, 0.1368],
         [0.4984, 0.5037, 0.2871],
         ...,
         [0.9687, 0.9057, 0.1842],
         [0.0543, 0.6691, 0.4571],
         [0.6771, 0.5773, 0.6711]],

        ...,

        [[0.9810, 0.8122, 0.8538],
         [0.6358, 0.7406, 0.5409],
         [0.2094, 0.1205, 0.0052],
         ...,
         [0.1101, 0.0920, 0.3256],
         [0.5611, 0.9817, 0.7855],
         [0.7013, 0.1033, 0.0844]],

        [[0.9632, 0.9988, 0.2247],
         [0.8677, 0.0014, 0.5855],
         [0.

In [ ]:
x_permuted

tensor([[[0.0000, 0.6513, 0.8718,  ..., 0.5216, 0.5900, 0.6719],
         [0.5385, 0.7184, 0.6324,  ..., 0.9176, 0.4619, 0.4695],
         [0.6162, 0.2231, 0.4984,  ..., 0.9687, 0.0543, 0.6771],
         ...,
         [0.9810, 0.6358, 0.2094,  ..., 0.1101, 0.5611, 0.7013],
         [0.9632, 0.8677, 0.9781,  ..., 0.6595, 0.2869, 0.3221],
         [0.3643, 0.5965, 0.5926,  ..., 0.4661, 0.4924, 0.3008]],

        [[0.8617, 0.7785, 0.9740,  ..., 0.5043, 0.8297, 0.2106],
         [0.0739, 0.6594, 0.3695,  ..., 0.1167, 0.8271, 0.2062],
         [0.9073, 0.9649, 0.5037,  ..., 0.9057, 0.6691, 0.5773],
         ...,
         [0.8122, 0.7406, 0.1205,  ..., 0.0920, 0.9817, 0.1033],
         [0.9988, 0.0014, 0.6997,  ..., 0.9274, 0.8914, 0.4417],
         [0.5568, 0.7875, 0.5723,  ..., 0.4151, 0.8152, 0.5361]],

        [[0.3533, 0.1573, 0.5367,  ..., 0.6005, 0.4711, 0.3447],
         [0.1721, 0.6479, 0.1323,  ..., 0.5191, 0.9200, 0.7225],
         [0.7120, 0.1368, 0.2871,  ..., 0.1842, 0.4571, 0.

### Indexing (selecting data from Tensors)

In [ ]:
import torch

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0, 1, 1]

tensor(5)

In [ ]:
# Get all values of 0th and 1st dimention but only index 1 of 2nd dimention
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[:, 0, :]

tensor([[1, 2, 3]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[:, 2, :]

tensor([[7, 8, 9]])

In [ ]:
x[:, 2, 2]

tensor([9])

### PyTorch Tensors and NumPy(Python Numerical Computing Library)

Data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)

pytorch tensor to numpy array -> torch.Tensor.numpy()

In [ ]:
# NumPy array to Tensor
import torch
import numpy as np

In [ ]:
array = np.arange(1.0, 8.0)
TENSOR = torch.from_numpy(array)
array, array.dtype, TENSOR

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
TENSOR.dtype

torch.float64

In [ ]:
array_32 = array.astype('float32')
TENSOR_32 = torch.from_numpy(array_32)
TENSOR_32, TENSOR_32.dtype, array_32.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32, dtype('float32'))

In [ ]:
help(torch.from_numpy)

Help on built-in function from_numpy in module torch:

from_numpy(...)
    from_numpy(ndarray) -> Tensor
    
    Creates a :class:`Tensor` from a :class:`numpy.ndarray`.
    
    The returned tensor and :attr:`ndarray` share the same memory. Modifications to
    the tensor will be reflected in the :attr:`ndarray` and vice versa. The returned
    tensor is not resizable.
    
    It currently accepts :attr:`ndarray` with dtypes of ``numpy.float64``,
    ``numpy.float32``, ``numpy.float16``, ``numpy.complex64``, ``numpy.complex128``,
    ``numpy.int64``, ``numpy.int32``, ``numpy.int16``, ``numpy.int8``, ``numpy.uint8``,
    and ``numpy.bool``.
    
    .. warning::
        Writing to a tensor created from a read-only NumPy array is not supported and will result in undefined behavior.
    
    Example::
    
        >>> a = numpy.array([1, 2, 3])
        >>> t = torch.from_numpy(a)
        >>> t
        tensor([ 1,  2,  3])
        >>> t[0] = -1
        >>> a
        array([-1,  2,  3])


In [ ]:
# tensor to numpy
T = torch.ones(7)
T

tensor([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
numpy_tensor = T.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
T = T + 1
T, T.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

### PyTorch Reproducbility (Trying to take random out of random)

In [ ]:
import torch

In [ ]:
# to reduce the randomness in neural networks and PyTorch comes the concept of a random seed
# Essentially what the random seed does is flavour the ransomness

rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

rand_tensor_A, rand_tensor_B

(tensor([[0.3332, 0.4271, 0.6712, 0.0072],
         [0.9510, 0.6182, 0.8663, 0.0315],
         [0.2151, 0.2172, 0.3443, 0.1364]]),
 tensor([[0.6317, 0.7789, 0.1593, 0.2938],
         [0.8837, 0.5939, 0.1900, 0.4393],
         [0.2559, 0.2152, 0.7369, 0.4502]]))

In [ ]:
rand_tensor_A == rand_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

rand_tensor_A, rand_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [ ]:
rand_tensor_A == rand_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# use the seed for every random number generating block of code
torch.manual_seed(RANDOM_SEED)
rand_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_B = torch.rand(3, 4)

print(rand_tensor_A)
print(rand_tensor_B)

rand_tensor_A == rand_tensor_B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPU (making faster computation)

In [ ]:
import torch

In [ ]:
# Setup device agnostic with pytorch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Putting tensors (and models) on the GPU

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# move tensor to gpu, if abailable
TENSOR_GPU = tensor.to(device)
tensor.device

device(type='cpu')

In [ ]:
TENSOR_GPU

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, can't transform it to numpy
TENSOR_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
TENSOR_CPU = TENSOR_GPU.cpu().numpy()
TENSOR_CPU

array([1, 2, 3])

## EXERCISE AND EXTRA-CURRICULUM

In [ ]:
import torch

In [ ]:
T1 = torch.rand(7, 7)
T2 = torch.rand(1, 7)
T1, T2

(tensor([[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
         [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
         [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
         [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
         [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
         [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237],
         [0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]]),
 tensor([[0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730]]))

In [ ]:
torch.matmul(T1, T2.reshape(7, 1))

tensor([[2.4911],
        [2.1696],
        [1.5092],
        [1.6439],
        [2.3490],
        [1.4221],
        [1.1739]])

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
T1 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
T2 = torch.rand(1, 7)
T1, T2

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [ ]:
torch.matmul(T1, T2.reshape(7, 1))

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
RANDOM_SEED = 0
if torch.cuda.is_available():
  torch.cuda.manual_seed(RANDOM_SEED)
  print('gpu')
else:
  torch.manual_seed(RANDOM_SEED)
  print('cpu')

cpu


In [ ]:
# Create two random tensors of shape (2, 3)
# and send them both to the GPU (you'll need access to a GPU for this).
#Set torch.manual_seed(1234) when creating the tensors
# (this doesn't have to be the GPU random seed)

import torch
RANDOM_SEED = 1234

In [ ]:
torch.manual_seed(RANDOM_SEED)
T1 = torch.rand(2, 3)
T2 = torch.rand(2, 3)
T1, T1

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [ ]:
if torch.cuda.is_available():
  T1_GPU = T1.to('cuda')
  T2_GPU = T2.to('cuda')
  print('gpu')
else:
  print('cpu')
T1_GPU.device, T2_GPU.device

gpu


(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
# Perform a matrix multiplication on the tensors you created

output = torch.matmul(T1_GPU, T2_GPU.T)
output, output.size

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 <function Tensor.size>)

In [ ]:
# Find the maximum and minimum values of the output
output_max = torch.max(output)
output_min = torch.min(output)
output_max, output_min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
# Find the maximum and minimum index values of the output
arg_max = torch.argmax(output)
arg_min = torch.argmin(output)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
'''
Make a random tensor with shape (1, 1, 1, 10)
and then create a new tensor with all the 1 dimensions removed
to be left with a tensor of shape (10).
Set the seed to 7 when you create it and print out the first tensor and it's
shape as well as the second tensor and it's shape
'''
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
T = torch.rand(1, 1, 1, 10)
T, T.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
T_squeeze = torch.squeeze(T)
T_squeeze, T_squeeze.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

## A PyTorch Workflow module